import React from 'react';
import clsx from 'clsx';
import styles from './styles.module.css';

const FeatureList = [
  {
    title: 'Asterisk Add-on',
    image: './img/asterisk_icon.png',
    description: (
      <>
        The Asterisk Add-on is a PBX server, made for the SIP card. With autogenerated extensions
        and preconfigured settings it is the easiest way to get started.
      </>
    ),
  },
  {
    title: 'SIP Card',
    image: './img/asterisk_logo.png',
    description: (
      <>
        The SIP Card allows you to call other dashboards and SIP devices like doorbells, from a Home Assistant dashboard.
      </>
    ),
  },
  {
    title: 'Asterisk Integration',
    image: './img/asterisk_logo.png',
    description: (
      <>
        Connects to the <b>AMI</b> and creates devices for the server and every SIP contact.
        Also includes services like <code>Hangup</code> or <code>Originate</code>.
      </>
    ),
  },
];

function Feature({image, title, description}) {
  return (
    <div className={clsx('col col--4')}>
      <div className="text--center">
        <img className={styles.featureSvg} src={image} />
      </div>
      <div className="text--center padding-horiz--md">
        <h3>{title}</h3>
        <p>{description}</p>
      </div>
    </div>
  );
}

export default function HomepageFeatures() {
  return (
    <section className={styles.features}>
      <div className="container">
        <div className="row">
          {FeatureList.map((props, idx) => (
            <Feature key={idx} {...props} />
          ))}
        </div>
      </div>
    </section>
  );
}
