name: Update Submodules

on:
  repository_dispatch:
    types: [update-docs]

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PAT }}
      - name: Update git submodules
        run: |
          git submodule update --init --recursive --remote -f
      - uses: EndBug/add-and-commit@v9
        with:
            default_author: github_actions
            message: 'Update submodules'
